DROP DATABASE IF EXISTS burger_db;
CREATE DATABASE burger_db;
USE burger;
CREATE TABLE burgers(
id INT AUTO_INCREMENT,
burger_name VARCHAR(50) NOT NULL,
devoured BOOL,
PRIMARY KEY(id)
)

CREATE TABLE burgers
